### ISSUE TITLE
Input - really slow mouse movements not detected downwards or rightwards

### ISSUE THREAD

**Issue by ldmldmldm** [Cloudef/wlc#181] opened 2016-08-11 01:44 UTC
Hi.

Moving really slowly (like 0.3cm/sec) results in the cursor not moving at all.
- _Only_ occurs when moving **downwards** or **rightwards**.
- Does not occur when moving upwards or leftwards.
- Occurs for the apple **touchpad** and some mouse.
- Does not occur under libinput on X11 or weston.

Note: on the touchpad I start from the middle to avoid any of the palm detection (which triggers if you start from top left or top right)

I confirmed I am using libinput on X using

```
arch:~$ grep -e "Using input driver " ~/.local/share/xorg/Xorg.0.log
[ 25022.988] (II) Using input driver 'libinput' for 'USB Optical Mouse'
[ 25023.031] (II) Using input driver 'libinput' for 'bcm5974'
```

My sway settings:

```
input "1133:49242:Logitech_USB_Optical" {
    accel_profile flat
}

input "7247:3:SIGMACHIP_Usb_Mou"{
    accel_profile flat
}

input "5426:67:Razer_Razer_DeathAdder_Chr" {
    accel_profile flat
}

input "1452:594:Apple_Inc._Apple_Internal_Keyboard_\/_Trac" {
    accel_profile flat
    tap enabled
    scroll_method two_finger
    dwt enabled
    natural_scroll enabled
}

input "1452:594:bcm" {
    accel_profile flat
    tap enabled
    scroll_method two_finger
    dwt enabled
    natural_scroll enabled
}
```

My X11 settings:

```
Section "InputClass"
    Identifier "libinput touchpad catchall"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    Driver "libinput"

    Option "Tapping" "true"
    Option "NaturalScrolling" "true"
    Option "DisableWhileTyping" "true"
    Option "ScrollMethod" "twofinger"

    Option "AccelProfile" "flat"
EndSection
```

Version info:

```
arch:~$ pacman -Qi wlc-git
Version         : 0.0.5-1
arch:~$pacman -Qi sway-git
Version         : r1863.49afdb4-1
arch:~$ sway -v
sway version 0.9-38-g49afdb4 (2016-08-10, branch "master")
```

Thanks.

**Comment by ldmldmldm** [comment] 2016-08-11 01:49
@psgarsenal no https://github.com/Cloudef/wlc/issues/166#issuecomment-237883598 does not solve the issue. I believe the profile is already flat, and there is something else screwing with the cursor when going rightwards and downwards.

**Comment by Cloudef** [comment] 2016-08-11 11:08
Do you have this issue with weston?

**Comment by ldmldmldm** [comment] 2016-08-12 03:01
No. Weston works perfectly (with mouse and touchpad) in all directions.

**Comment by psgarsenal** [comment] 2016-08-29 06:48
Ok so I did some testing, and it turns out that "accel_profile flat" in sway does not solve my issue, and that it does not appear in weston, so this issue and mine (#166) are the same

**Comment by ldmldmldm** [comment] 2016-08-31 00:09
Every mouse (and the touchpad) I have tried causes this issue, not only hi-dpi mice. I've tried with 400dpi, 800dpi, and 1200dpi mice.

**Comment by psgarsenal** [comment] 2016-08-31 06:23
Symptoms were the same explained differently, i cannot move my mouse slowly, in the down-right direction, I just thought moving it in circle would show it better on video.
It must be something with the hardware acting in a different way than "traditional mice", since, as you can see in my issue, a 5 buck mouse don't have this problem.

**Comment by ldmldmldm** [comment] 2016-08-31 07:01
The issue is so bad on the apple touchpad I would say sway is unusable.

**Comment by zenmetsu** [comment] 2017-06-19 21:45
Issue still persists as of wlc 0.0.9
I am using a Logitech TrackMan Wheel
`Bus 001 Device 004: ID 046d:c404 Logitech, Inc. TrackMan Wheel`

I also replicated the behavior with a handful of random mice at the office, including a Dell optical mouse, so I do not believe it to be related to the hardware, per se.  This has to be a silly math error somewhere.

I'm not familiar with this project, but I'll take a shot at trying to fork&fix since there doesn't appear to be much traction on this issue.  Setting the accel_profile to flat within Sway fixed the problem, but losing the adaptive acceleration is not acceptable.

**Comment by ascent12** [comment] 2017-07-12 01:20
I should note that I haven't tested this, so I could be completely wrong about what I'm saying.

The problem is actually pretty simple, and has nothing to do with your hardware. I dealt with the exact same problem briefly while working on https://github.com/SirCmpwn/wlroots.
It's just a rounding error that is happening somewhere, particularly one from a floating point to an integer. Small updates are simply being rounded away. I fixed this by changing how the cursor position is stored from an integer to a floating point number, and only let it be rounded at the very end when we need to actually draw the cursor.

WLC **seems** to do the correct thing. It stores all of the pointer positions and motion as double, so there shouldn't be a problem with rounding.
However, after digging around a little bit, I think I found where it happens. Unfortunately, it happens in the worst place possible: the API.

Looking at wlc/wlc.h:
```c
/** Motion event was triggered, view handle will be zero if there was no focus. Apply with wlc_pointer_set_position to agree. Return true to prevent sending the event to clients. */
void wlc_set_pointer_motion_cb(bool (*cb)(wlc_handle view, uint32_t time, const struct wlc_point*));

/** Set current pointer position. */
void wlc_pointer_set_position(const struct wlc_point *position);
```
So the user needs to explicitly set the pointer after some motion happens. This alone isn't a bad thing, but looking at the definition of struct wlc_point:
```c
struct wlc_point {
   int32_t x, y;
};
```
An integer type.
So whenever some pointer motion happens, it gets rounded whenever the user hears about it.

The obvious fix is change struct wlc_point to some other type using double/float, but unfortunately this is a breaking change in terms of both the API and ABI, and may require users to change their code a little bit.

WLC is going to be abandoned anyway, so I don't know if this is the sort of change you would be bothered doing.
@SirCmpwn @Enerccio

**Comment by Timidger** [comment] 2017-07-12 01:39
As annoying as of a problem as this is now (and one I have ran into), there are numerous problems that I have run into with wlc already that will be fixed in wlroots. I suggest to not fix this now and let wlroots fix this. Obviously if ewlc wants to fix this, I see no problem with that as I don't explicitly support that in Way Cooler.

**Comment by SirCmpwn** [comment] 2017-07-12 01:53
I wouldn't mind just making a new API for doing it more precisely. `wlc_set_pointer_motion_v2_cb` or something similar.

**Comment by ascent12** [comment] 2017-07-12 02:02
>`wlc_set_pointer_motion_v2_cb`

That would probably be the easiest fix. It also needs a `wlc_pointer_set_position_v2` to go along with it.

**Closed** 2017-07-12 11:06 UTC
Labels: input
