### ISSUE TITLE
Request for modesetting support

### ISSUE THREAD

**Issue by hashashini** [Cloudef/wlc#164] opened 2016-05-02 14:11 UTC
Request support for custom modes, like e.g. in weston, cf. https://wiki.archlinux.org/index.php/wayland#Configuration (second [output]-section from bottom in ~/.config/weston.ini).

**Comment by Cloudef** [comment] 2016-05-02 15:03
Duplicate of https://github.com/Cloudef/wlc/issues/37

**Closed by Cloudef** 2016-05-02 15:03 UTC
