### ISSUE TITLE
XWayland application scaling

### ISSUE THREAD

**Issue by handijk** [Cloudef/wlc#268] opened 2017-05-23 18:45 UTC
XWayland applications are scaled up from their rendered size if output scaling is enabled, this results in blurry and low res applications, to prevent this XWayland applications should be set to render at a set scale, per output (because the scaling could differ per output).

**Comment by SirCmpwn** [comment] 2017-05-23 18:45
Dupe of: https://github.com/Cloudef/wlc/issues/225

Xwayland does not support per-output scaling.

**Closed by SirCmpwn** 2017-05-23 18:45 UTC
