### ISSUE TITLE
Better input configuration

### ISSUE THREAD

**Issue by SirCmpwn** [Cloudef/wlc#61] opened 2015-08-23 17:20 UTC
Particularly around things like mouse/touchpad/tablet input.

**Comment by Cloudef** [comment] 2015-08-23 17:22
Duplicate of #6, closing.

**Comment by SirCmpwn** [comment] 2015-08-23 17:23
Sorry, not sure how I missed that one.

**Closed by Cloudef** 2015-08-23 17:22 UTC

**Comment by Cloudef** [comment] 2015-08-23 17:27
It happens :)
