### ISSUE TITLE
Pointer event issues with latest xorg-server-*

### ISSUE THREAD

**Issue by SirCmpwn** [Cloudef/wlc#88] opened 2015-11-24 13:21 UTC
Pointer events are being sent to the wrong client. If I open an x client on output 1 and another on output 2, regardless of where focus is, the events will all go to output 1's client.

**Comment by somebears** [comment] 2015-11-24 23:47
Creating a second client on output 1 and moving it to output 2 has the same result. Works as intended while on output 1 (even when moved back)

**Comment by somebears** [comment] 2015-11-26 11:36
Another oddity that might help to fix this major issue fast is:

I opened vlc player on my 2nd output and then chromium on the first. Now I am unable to use my mouse to control vlc. However, chromium's upper edges are rounded and transparent. If I click on the top left of my screen I am able to invoke the menu of vlc.

Odd enough by itself, I can also invoke the menu if I click the top right(and only there, the rest is unresponsive) on the 2nd view.

It seems to me like both clients reside on both views, but are only visible on their respective views. This is somewhat confirmed by resizing the 2nd client resulting in a partially accessible 1st client

**Comment by Cloudef** [comment] 2015-11-26 13:05
It's exactly how xwayland works. To wayland xwayland is just 1 client, all the view inside are surfaces. The xwayland receives input _globally_. This breakage is either regression or change how compositors should handle the input for X11 programs.

**Comment by SirCmpwn** [comment] 2015-11-28 13:52
Bump. Any news? This is a pretty bad one.

**Comment by Earnestly** [comment] 2015-11-28 14:26
Running with `WLC_DEBUG=xwm` I'm not seeing any `FOCUS_OUT` event when switching workspaces while focus events properly trigger when rotating through xwayland clients.

The code reponsible for these particular events appears to be unimplimented? [xwm.c:863](https://github.com/Cloudef/wlc/blob/master/src/xwayland/xwm.c#L863-L881) (Compared with `FOCUS_IN`: [xwm.c:804](https://github.com/Cloudef/wlc/blob/master/src/xwayland/xwm.c#L804))

**Comment by SirCmpwn** [comment] 2015-11-28 14:32
That looks like a promising lead.

**Closed** 2015-11-30 20:17 UTC
