### ISSUE TITLE
xterm right-click context menu is shown only once

### ISSUE THREAD

**Issue by tuncer** [Cloudef/wlc#175] opened 2016-06-24 17:38 UTC
After the first time the right-click context menu in xterm has been displayed, any future invocation has no visible effect.

**Comment by VoidNoire** [comment] 2016-08-15 10:00
This might be a dupe of #104 and SirCmpwn/sway#571

**Comment by tuncer** [comment] 2017-08-21 00:46
The menu doesn't appear only once anymore, but it's janky and doesn't seem to draw borders correctly. I can enter and leave the context menu repeatedly. Does this mean it has been fixed?

**Closed** 2018-05-31 11:50 UTC
